version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pharmacy-laravel-app
    container_name: pharmacy_app
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:fXW1REFgsUw8sBZgmGLj2NHP2wuj2835dud65HBGaMI=
      - DB_CONNECTION=mysql
      - DB_HOST=gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com
      - DB_PORT=4000
      - DB_DATABASE=test
      - DB_USERNAME=2e3Sc56gvZdX7fd.root
      - DB_PASSWORD=r3XVhhhDCR3UpyI5
      - MYSQL_ATTR_SSL_CA=isrgrootx1.pem
      - DB_SSL_VERIFY=false
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=kareemelbalshe1234@gmail.com
      - MAIL_PASSWORD=laolrbpbmffuvdtf
      - MAIL_ENCRYPTION=tls
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    networks:
      - pharmacy-network

networks:
  pharmacy-network:
    driver: bridge
